/**
 * OmniKit Tools — master name registry.
 * 750 real tools across 12 categories. Names are human-authored;
 * slugs are derived deterministically and asserted unique at build time.
 *
 * Counts: developer 80 · pdf 70 · image 70 · css 50 · seo 50 · finance 55 ·
 *         security 45 · converters 85 · network 45 · productivity 60 ·
 *         media 55 · text 85  →  750 total
 */

export type CategorySlug =
  | "developer"
  | "pdf"
  | "image"
  | "css"
  | "seo"
  | "finance"
  | "security"
  | "converters"
  | "network"
  | "productivity"
  | "media"
  | "text";

/** Slugs rendered by bespoke interactive components (hero tools). */
export const COMPONENT_SLUGS: string[] = [
  // Developer
  "json-formatter", "base64-encoder", "base64-decoder", "regex-tester",
  "uuid-generator", "jwt-decoder", "number-base-converter", "qr-code-generator",
  "url-encoder", "url-decoder", "timestamp-converter", "epoch-converter",
  // Text
  "word-counter", "case-converter", "lorem-ipsum-generator", "slug-generator",
  "text-reverser", "find-and-replace-tool", "text-diff-checker", "text-compare-tool",
  "text-to-speech-converter", "speech-to-text-converter", "text-statistics-analyzer",
  // Security
  "password-generator", "password-strength-checker", "password-analyzer",
  "hash-generator", "md5-hash-generator", "sha-1-hash-generator",
  "sha-256-hash-generator", "sha-512-hash-generator", "crc32-checksum-calculator",
  "password-leak-checker", "totp-code-generator", "otp-generator",
  "key-pair-generator", "data-encryption-tool", "data-decryption-tool",
  "secure-note-encrypter", "wifi-password-generator", "pin-generator",
  "passphrase-generator",
  // Converters
  "color-converter", "unit-converter", "unix-timestamp-converter",
  "date-to-unix-timestamp", "unix-to-date", "utc-converter",
  "length-converter", "weight-converter", "temperature-converter", "area-converter",
  "volume-converter", "speed-converter", "data-storage-converter", "time-converter",
  "energy-converter", "pressure-converter", "power-converter", "frequency-converter",
  "angle-converter", "torque-converter", "fuel-efficiency-converter",
  "cooking-unit-converter", "metric-to-imperial-converter", "imperial-to-metric-converter",
  "kilometers-to-miles", "miles-to-kilometers", "meters-to-feet", "feet-to-meters",
  "centimeters-to-inches", "inches-to-centimeters", "kilograms-to-pounds",
  "pounds-to-kilograms", "grams-to-ounces", "ounces-to-grams", "liters-to-gallons",
  "gallons-to-liters", "celsius-to-fahrenheit", "fahrenheit-to-celsius",
  "celsius-to-kelvin", "kelvin-to-celsius", "fahrenheit-to-kelvin", "kelvin-to-fahrenheit",
  "mph-to-kph", "kph-to-mph", "knots-to-mph", "mb-to-gb", "gb-to-tb", "bytes-to-kb",
  "bits-to-bytes", "megabits-to-megabytes", "mbps-to-mbps",
  "hex-to-rgb", "rgb-to-hex", "hex-to-hsl", "hsl-to-hex", "rgb-to-hsl", "hsl-to-rgb",
  "hex-to-cmyk", "cmyk-to-hex", "rgb-to-cmyk", "cmyk-to-rgb", "rgb-to-hsv", "hsv-to-rgb",
  // Finance
  "loan-calculator", "mortgage-calculator", "auto-loan-calculator",
  "personal-loan-calculator", "emi-calculator", "amortization-schedule-generator",
  "compound-interest-calculator", "simple-interest-calculator", "investment-calculator",
  "retirement-calculator", "savings-calculator", "sip-calculator", "inflation-calculator",
  "fire-calculator", "retirement-savings-calculator", "tip-calculator",
  "bmi-calculator", "percentage-calculator", "sales-tax-calculator", "vat-calculator",
  "gst-calculator", "discount-calculator", "percentage-change-calculator",
  "markup-calculator", "margin-calculator",
  // Image
  "image-to-base64", "image-resizer", "image-metadata-viewer", "color-palette-extractor",
  // SEO
  "meta-tag-preview", "serp-preview-tool", "keyword-density-checker",
  "robots-txt-generator",
  // Network
  "ip-address-lookup", "what-is-my-ip", "user-agent-parser",
  "http-status-code-checker", "url-parser",
  // CSS
  "gradient-generator", "box-shadow-generator", "border-radius-generator",
  // Media
  "color-blindness-simulator", "word-cloud-generator", "metronome",
  "music-bpm-counter", "audio-spectrum-visualizer",
  // Productivity
  "pomodoro-timer", "focus-timer", "break-timer", "work-session-timer",
  "ambient-sound-timer", "study-timer", "task-timer", "countdown-timer",
  "markdown-to-html", "markdown-editor", "stopwatch", "world-clock",
  // PDF
  "text-to-pdf", "pdf-metadata-generator",
];

export const TOOL_NAMES: Record<CategorySlug, string[]> = {
  developer: [
    "JSON Formatter", "Base64 Encoder", "Base64 Decoder", "Regex Tester",
    "UUID Generator", "JWT Decoder", "Number Base Converter", "QR Code Generator",
    "URL Encoder", "URL Decoder", "Timestamp Converter", "JSON Minifier",
    "JSON Validator", "JSON to CSV", "JSON to XML", "JSON to YAML",
    "YAML to JSON", "XML to JSON", "CSV to JSON", "JSON Tree Viewer",
    "JSON Path Evaluator", "JSON Schema Generator", "JSON Random Generator",
    "JSON Escape Tool", "JSON Diff Checker", "HTML Entity Encoder",
    "HTML Entity Decoder", "HTML Minifier", "CSS Minifier", "JS Minifier",
    "XML Formatter", "YAML Formatter", "YAML Validator", "CSV Formatter",
    "CSV Parser", "Regex Generator", "Regex Escape Tool", "ULID Generator",
    "NanoID Generator", "JWT Generator", "Cron Expression Generator",
    "Cron Expression Parser", "Barcode Generator", "Curl to Code Converter",
    "GraphQL Formatter", "SQL Formatter", "SQL to JSON Converter",
    "HTML to JSX Converter", "JS to TypeScript Converter",
    "TypeScript to JavaScript Converter", "Color Picker for Developers",
    "Binary to Decimal", "Hex to Decimal", "Octal to Decimal",
    "Decimal to Binary", "Decimal to Hex", "Binary to Hex", "Hex to Binary",
    "Binary to Text", "Text to Binary", "Hexadecimal to Text",
    "Text to Hexadecimal", "ASCII Table Reference", "Morse Code Translator",
    "String Length Counter", "Random String Generator", "Mock Data Generator",
    "API Response Tester", "REST Client Simulator", "Webhook Tester",
    "JSON Beautifier", "Protobuf Decoder", "Epoch Converter",
    "Unicode Code Point Lookup", "Unicode Escape Converter", "RegExp Visualizer",
    "DNS Record Generator", "Gitignore Generator", "README Generator",
    "JSON to Text",
  ],
  pdf: [
    "Text to PDF", "PDF Metadata Generator", "PDF Merge", "PDF Split",
    "PDF Compress", "PDF Rotate", "PDF Watermark", "PDF Page Remover",
    "PDF Page Extractor", "PDF Page Reorder", "PDF Reverse Pages",
    "PDF to JPG", "PDF to PNG", "PDF to Text", "PDF to Word", "PDF to Excel",
    "PDF to PowerPoint", "PDF to HTML", "PDF to Base64", "Base64 to PDF",
    "PDF Metadata Viewer", "PDF Metadata Editor", "PDF Signature Creator",
    "PDF Stamp Tool", "PDF Annotator", "PDF Redactor", "PDF Cropper",
    "PDF Page Counter", "PDF Page Sizer", "PDF Orientation Changer",
    "PDF Encryption Tool", "PDF Decryption Tool", "PDF Repair Tool",
    "PDF Optimization Analyzer", "PDF Font Extractor", "PDF Image Extractor",
    "PDF Text Extractor", "PDF Color Mode Converter", "PDF Margin Adder",
    "PDF Bookmark Editor", "PDF Index Generator",
    "PDF Table of Contents Builder", "PDF Cover Page Maker", "PDF Barcode Adder",
    "PDF Page Numbering Tool", "PDF Header Footer Adder", "PDF Bleed Calculator",
    "PDF Trim Box Calculator", "PDF DPI Checker", "PDF File Size Calculator",
    "PDF Color Counter", "PDF Ink Coverage Analyzer", "PDF Accessibility Checker",
    "PDF Link Extractor", "PDF Compare Tool", "PDF Blank Page Remover",
    "PDF Odd Even Splitter", "PDF Batch Renamer", "PDF Duplicate Finder",
    "PDF Archive Creator", "PDF Compression Estimator", "PDF Word Count Tool",
    "PDF Unlock Analyzer", "PDF Form Filler", "PDF Fillable Form Creator",
    "PDF Highlight Extractor", "PDF Drawing Tool", "PDF Print Optimizer",
    "PDF Backup Tool", "PDF to PDF/A Converter",
  ],
  image: [
    "Image to Base64", "Image Resizer", "Image Metadata Viewer",
    "Color Palette Extractor", "Image Compressor", "Image Cropper",
    "Image Rotator", "Image Flipper", "Image Format Converter", "PNG to JPG",
    "JPG to PNG", "WebP to PNG", "PNG to WebP", "Image Grayscale Converter",
    "Image Negative Converter", "Image Brightness Adjuster",
    "Image Contrast Adjuster", "Image Saturation Adjuster", "Image Blur Tool",
    "Image Sharpen Tool", "Image Pixelate Tool", "Image Sepia Filter",
    "Image Vintage Filter", "Image Invert Tool", "Image Mirror Tool",
    "Image Watermark Adder", "Image Metadata Remover", "EXIF Data Viewer",
    "Image Color Picker", "Dominant Color Finder",
    "Image Aspect Ratio Calculator", "Image Rounder", "Image Border Adder",
    "Image Shadow Adder", "Rounded Corners Tool", "Image Text Overlay",
    "Meme Generator", "Screenshot Cropper", "Photo Collage Maker",
    "Image Splitter", "Image Combiner", "Image Stitcher",
    "Sprite Sheet Generator", "Favicon Generator", "Icon Resizer",
    "App Icon Generator", "OG Image Generator", "Banner Generator",
    "Social Media Image Resizer", "Passport Photo Maker", "ID Photo Resizer",
    "Photo Editor Lite", "Pixel Art Maker", "Dithering Tool", "Image Quantizer",
    "Image Histogram Viewer", "Image Noise Generator",
    "Gradient Image Generator", "QR Image Decoder", "Image Data URL Encoder",
    "SVG to PNG", "PNG to SVG", "SVG Optimizer", "SVG Minifier", "SVG Viewer",
    "Animated GIF Optimizer", "GIF Frame Extractor", "APNG to GIF",
    "ICO Converter", "Thumbnail Generator",
  ],
  css: [
    "Gradient Generator", "Box Shadow Generator", "Border Radius Generator",
    "Text Shadow Generator", "CSS Triangle Generator", "CSS Filter Generator",
    "CSS Transform Generator", "CSS Transition Generator",
    "CSS Animation Generator", "Keyframe Generator", "Flexbox Generator",
    "Grid Generator", "CSS Grid Template Generator", "Flexbox Cheat Sheet",
    "Grid Cheat Sheet", "Glassmorphism Generator", "Neumorphism Generator",
    "Glass Effect Generator", "Clip Path Generator", "CSS Shapes Generator",
    "CSS Buttons Generator", "Button Generator", "Card Generator",
    "Badge Generator", "Loader Generator", "Spinner Generator",
    "Skeleton Loader Generator", "CSS Blob Generator", "CSS Pattern Generator",
    "Background Pattern Generator", "Linear Gradient Presets",
    "Radial Gradient Generator", "CSS Color Palette Generator",
    "CSS Variables Generator", "CSS Reset Generator", "Media Query Generator",
    "Responsive Breakpoint Tester", "CSS Specificity Calculator",
    "CSS Unit Converter", "PX to REM Converter", "REM to PX Converter",
    "PX to EM Converter", "EM to PX Converter", "VW Calculator",
    "Aspect Ratio CSS Generator", "Z-Index Helper", "CSS Selector Builder",
    "CSS Curtain Generator", "CSS Ribbon Generator",
    "Glassmorphism Preview Tool",
  ],
  seo: [
    "Meta Tag Preview", "Keyword Density Checker", "Robots.txt Generator",
    "URL Slug Generator", "Meta Tag Generator", "Meta Description Generator",
    "Open Graph Generator", "Twitter Card Generator", "SERP Preview Tool",
    "Sitemap Generator", "XML Sitemap Validator", "Schema Markup Generator",
    "FAQ Schema Generator", "Breadcrumb Schema Generator",
    "Local Business Schema Generator", "Product Schema Generator",
    "Article Schema Generator", "JSON-LD Validator", "Structured Data Tester",
    "Canonical URL Checker", "Slug Optimizer", "Title Tag Optimizer",
    "Title Tag Length Checker", "Meta Description Length Checker",
    "Header Tag Checker", "H1 Extractor", "Alt Text Generator",
    "Image Alt Tag Checker", "Broken Link Checker", "Redirect Checker",
    "301 Redirect Generator", ".htaccess Generator", "Robots Meta Generator",
    "Noindex Checker", "Page Speed Analyzer", "Core Web Vitals Calculator",
    "Mobile Friendly Tester", "Keyword Position Simulator", "Keyword Combiner",
    "Long Tail Keyword Generator", "Keyword Permutation Tool",
    "Google Index Checker", "Search Intent Analyzer", "Rich Snippet Preview",
    "Review Schema Generator", "FAQ Page Builder", "SERP Feature Finder",
    "Content Length Checker", "Readability Score", "Keyword Research Assistant",
  ],
  finance: [
    "Loan Calculator", "Compound Interest Calculator", "Tip Calculator",
    "BMI Calculator", "Percentage Calculator", "Mortgage Calculator",
    "Auto Loan Calculator", "Personal Loan Calculator", "Simple Interest Calculator",
    "Investment Calculator", "Retirement Calculator", "Savings Calculator",
    "SIP Calculator", "EMI Calculator", "Debt Payoff Calculator",
    "Credit Card Payoff Calculator", "Budget Calculator", "Salary Calculator",
    "Hourly Wage Calculator", "Overtime Calculator", "Income Tax Estimator",
    "Sales Tax Calculator", "VAT Calculator", "GST Calculator",
    "Discount Calculator", "Percentage Change Calculator", "Markup Calculator",
    "Margin Calculator", "Profit Margin Calculator", "ROI Calculator",
    "Payback Period Calculator", "Break Even Calculator", "Inflation Calculator",
    "Currency Converter", "Crypto Profit Calculator", "Stock Profit Calculator",
    "Dividend Calculator", "APY Calculator", "APR Calculator",
    "Car Lease Calculator", "Rent Affordability Calculator",
    "Mortgage Refinance Calculator", "Down Payment Calculator",
    "Amortization Schedule Generator", "50/30/20 Budget Planner",
    "Emergency Fund Calculator", "Net Worth Calculator", "Cost Per Use Calculator",
    "Price Per Unit Calculator", "Fuel Cost Calculator",
    "Mileage Reimbursement Calculator", "Home Equity Calculator",
    "Freelance Rate Calculator", "FIRE Calculator", "Retirement Savings Calculator",
  ],
  security: [
    "Password Generator", "Password Strength Checker", "Hash Generator",
    "MD5 Hash Generator", "SHA-1 Hash Generator", "SHA-256 Hash Generator",
    "SHA-512 Hash Generator", "CRC32 Checksum Calculator",
    "Adler-32 Checksum Calculator", "HMAC Generator", "BCrypt Hash Generator",
    "Password Entropy Calculator", "Random Key Generator", "API Key Generator",
    "TOTP Code Generator", "OTP Generator", "Password Analyzer",
    "Password Leak Checker", "SSL Certificate Checker", "CORS Analyzer",
    "CSP Generator", "Security Headers Generator",
    "Secure Password Policy Generator", "Security Questions Generator",
    "Salt Generator", "Token Generator", "Key Pair Generator",
    "Certificate Signing Request Generator", "Base64 Cert Decoder",
    "JWT Secret Generator", "WiFi Password Generator", "Secret Sharing Tool",
    "Data Encryption Tool", "Data Decryption Tool", "File Encryption Tool",
    "File Hash Checker", "Password Manager CSV Checker",
    "Phishing Link Analyzer", "Hash Lookup Tool", "Zero-Knowledge Encoder",
    "Passphrase Generator", "PIN Generator", "Salt Hash Generator",
    "Secure Note Encrypter", "Cipher Text Encoder",
  ],
  converters: [
    "Color Converter", "Unit Converter", "Unix Timestamp Converter",
    "Length Converter", "Weight Converter", "Temperature Converter",
    "Area Converter", "Volume Converter", "Speed Converter",
    "Data Storage Converter", "Time Converter", "Energy Converter",
    "Pressure Converter", "Power Converter", "Frequency Converter",
    "Angle Converter", "Torque Converter", "Fuel Efficiency Converter",
    "Cooking Unit Converter", "Metric to Imperial Converter",
    "Imperial to Metric Converter", "Kilometers to Miles", "Miles to Kilometers",
    "Meters to Feet", "Feet to Meters", "Centimeters to Inches",
    "Inches to Centimeters", "Kilograms to Pounds", "Pounds to Kilograms",
    "Grams to Ounces", "Ounces to Grams", "Liters to Gallons",
    "Gallons to Liters", "Celsius to Fahrenheit", "Fahrenheit to Celsius",
    "Celsius to Kelvin", "Kelvin to Celsius", "Fahrenheit to Kelvin",
    "Kelvin to Fahrenheit", "Mph to Kph", "Kph to Mph", "Knots to Mph",
    "MB to GB", "GB to TB", "Bytes to KB", "Bits to Bytes",
    "Megabits to Megabytes", "Mbps to MBps", "Hex to RGB", "RGB to Hex",
    "Hex to HSL", "HSL to Hex", "RGB to HSL", "HSL to RGB", "Hex to CMYK",
    "CMYK to Hex", "RGB to CMYK", "CMYK to RGB", "RGB to HSV", "HSV to RGB",
    "Binary to Octal", "Octal to Binary", "Decimal to Octal", "Text to Base32",
    "Decimal to Roman", "Roman to Decimal", "ASCII to Hex", "Hex to ASCII",
    "ASCII to Binary", "Binary to ASCII", "Unicode to UTF-8", "UTF-8 to Unicode",
    "Decimal to ASCII", "ASCII to Decimal", "Morse Code to Text",
    "Text to Morse Code", "Military Time Converter",
    "12 Hour to 24 Hour Converter", "Date to Unix Timestamp", "Unix to Date",
    "UTC Converter", "Time Zone Converter", "Quoted Printable Encoder",
    "Quoted Printable Decoder", "Text to ROT13",
  ],
  network: [
    "IP Address Lookup", "What is My IP", "User Agent Parser",
    "HTTP Status Code Checker", "URL Parser", "IPv4 Subnet Calculator",
    "IP Range Calculator", "CIDR Calculator", "IPv4 to IPv6 Converter",
    "IPv6 to IPv4 Converter", "MAC Address Generator", "MAC Address Lookup",
    "MAC Address Format Converter", "Random IP Generator", "IP Geolocation Lookup",
    "User Agent Generator", "HTTP Header Analyzer", "HTTP Request Builder",
    "CORS Tester", "Ping Test", "DNS Lookup", "DNS Record Checker",
    "Reverse DNS Lookup", "WHOIS Lookup", "Domain Availability Checker",
    "Domain Name Generator", "Domain Age Calculator", "URL Shortener Decoder",
    "URL Expander", "Redirect Chain Checker", "WebSocket Tester", "Port Scanner",
    "Firewall Rule Generator", "Network Speed Test", "Latency Estimator",
    "Bandwidth Calculator", "Data Transfer Time Calculator",
    "Download Time Calculator", "Uptime Calculator", "WiFi Analyzer",
    "Network Prefix Calculator", "VLAN Calculator", "Proxy Checker",
    "Public IP Range Lookup", "Email Header Analyzer",
  ],
  productivity: [
    "Pomodoro Timer", "Countdown Timer", "Markdown to HTML",
    "Random Number Generator", "Coin Flip Simulator", "Dice Roller",
    "Stopwatch", "World Clock", "Reading Speed Calculator",
    "Words Per Minute Test", "Typing Speed Test", "Email Signature Generator",
    "Meeting Time Planner", "Time Zone Meeting Scheduler", "Daily Planner",
    "Weekly Planner Template Generator", "To-Do List Manager", "Habit Tracker",
    "Focus Timer", "Break Timer", "Work Session Timer", "Task Prioritizer",
    "Eisenhower Matrix Tool", "Kanban Board Generator", "Scrum Board Template",
    "Gantt Chart Planner", "Priority Matrix", "Decision Maker",
    "Random Choice Picker", "Random Name Picker", "Wheel of Fortune Spinner",
    "Number Picker", "Private Notes", "Note Taking Pad", "Markdown Editor",
    "HTML to Markdown", "Checklist Generator", "Progress Tracker", "Goal Planner",
    "SMART Goal Generator", "Habit Streak Calculator",
    "Words Per Minute Calculator", "Email Template Builder",
    "Email Subject Line Generator", "Memo Generator", "Invoice Generator",
    "Receipt Generator", "Expense Tracker", "Time Tracker", "Work Log Generator",
    "Standup Notes Generator", "Meeting Agenda Generator",
    "Meeting Minutes Template", "Idea Board", "Brainstorming Tool",
    "Mind Map Outline Generator", "Ambient Sound Timer", "Study Timer",
    "Productivity Score Calculator", "Task Timer",
  ],
  media: [
    "Color Blindness Simulator", "Word Cloud Generator", "Metronome",
    "Music BPM Counter", "Audio Spectrum Visualizer", "Aspect Ratio Calculator",
    "Pixels to Inches Calculator", "Inches to Pixels Calculator",
    "DPI Calculator", "PPI Calculator", "Contrast Ratio Checker",
    "Frame Rate Calculator", "Frame Time Calculator", "Retina Display Calculator",
    "Safe Area Calculator", "Audio Waveform Generator",
    "Audio Duration Calculator", "Video Duration Calculator",
    "File Size Calculator", "Media File Info Viewer", "Audio Bitrate Calculator",
    "Video Bitrate Calculator", "Video Resolution Calculator",
    "Streaming Bandwidth Calculator", "YouTube Thumbnail Preview",
    "YouTube Title Generator", "YouTube Description Generator",
    "YouTube Tag Generator", "YouTube Embed Code Generator",
    "Podcast Title Generator", "Podcast Episode Planner", "Audio Metadata Editor",
    "Video Aspect Ratio Calculator", "Subtitle Time Calculator", "SRT Generator",
    "Subtitle Shifter", "Lyrics Timestamp Formatter", "Voice Pitch Analyzer",
    "Noise Level Meter", "Chord Finder", "Guitar Tuner",
    "Poster Frame Extractor", "GIF Speed Changer", "Meme Text Generator",
    "Screenshot Mockup Generator", "Presentation Slide Timer",
    "Zoom Background Generator", "Streaming Quality Selector Guide",
    "Audio Format Converter", "Sample Rate Calculator", "Media Batch Renamer",
    "Emoji Art Generator", "Pixel to Point Converter", "Point to Pixel Converter",
    "Aspect Ratio Calculator Pro",
  ],
  text: [
    "Word Counter", "Case Converter", "Lorem Ipsum Generator", "Slug Generator",
    "Text Reverser", "Find and Replace Tool", "Text Diff Checker",
    "Text to Speech Converter", "Speech to Text Converter",
    "Fancy Text Generator", "Zalgo Text Generator", "Vaporwave Text Generator",
    "Upside Down Text Generator", "Pig Latin Translator",
    "Caesar Cipher Encoder", "Caesar Cipher Decoder", "Atbash Cipher Encoder",
    "Vigenere Cipher Encoder", "ROT13 Encoder", "L33t Speak Converter",
    "NATO Phonetic Alphabet Translator", "Braille Text Converter",
    "Character Counter", "Letter Counter", "Sentence Counter",
    "Paragraph Counter", "Line Counter", "Reading Time Calculator",
    "Speaking Time Calculator", "Uppercase Converter", "Lowercase Converter",
    "Title Case Converter", "Sentence Case Converter", "Camel Case Converter",
    "Pascal Case Converter", "Snake Case Converter", "Kebab Case Converter",
    "Alternating Case Converter", "Invert Case Converter", "Reverse Words Tool",
    "Reverse Lines Tool", "Text Sorter", "Alphabetical Sorter",
    "Number Sorter", "Line Sorter", "Dedupe Lines Tool",
    "Duplicate Line Remover", "Duplicate Word Remover", "Text Compare Tool",
    "Text Repeater", "Text Multiplier", "Text Randomizer", "Word Shuffler",
    "Letter Shuffler", "Text Truncator", "Text Shortener", "Text Expander",
    "Random Text Generator", "Random Word Generator",
    "Random Sentence Generator", "Random Paragraph Generator",
    "Acronym Generator", "Abbreviation Finder", "Anagram Solver",
    "Palindrome Checker", "Emoji Text Converter", "Bubble Text Generator",
    "Small Caps Text Generator", "Wingdings Translator", "Keyword Extractor",
    "Text Summarizer", "Sentence Rewriter", "Grammar Checker",
    "Plagiarism Checker", "Text Statistics Analyzer", "Word Frequency Counter",
    "N-gram Generator", "Markov Chain Text Generator", "Character Map",
    "Unicode Text Normalizer", "Whitespace Cleaner", "Line Break Remover",
    "Extra Space Remover", "HTML to Text", "Text to HTML",
  ],
};
